---
# Home Assistant Glow
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# © Klaas Schoute
#
substitutions:
  device_name: beetle-home-assistant-glow
  friendly_name: Beetle Home Assistant Glow
  project_version: "4.1.1"
  device_description: "Measure your energy consumption with the pulse LED on your smart meter - ESP32 Generic"

  # Define the GPIO pins
  pulse_pin: GPIO22
  # status_led: GPIO5
  # led_pin_red: GPIO2
  # led_pin_green: GPIO4

esphome:
  name: esp32c6-hidrophonics
  friendly_name: Beetle_home_assistant_glow
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "Dale-Muccignat.home-assistant-glow"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://Dale-Muccignat/home-assistant-glow/home-assistant-glow/esp32.yaml@main

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: 6.8.1

packages:
  remote_package:
    url: https://github.com/Dale-Muccignat/home-assistant-glow/
    ref: "4.1.1"
    files:
      - components/basis.yaml
      - components/pulse_meter.yaml

# Enable logging
logger:
  level: VERBOSE

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# To have a "next url" for improv serial
web_server:
